### PR TITLE
fix for keytool issues on windows and missing bigsql service

### PR DESCRIPTION
**Pull request by snowch**

### CODE REVIEW

**Comment by snowch** [comment]
@pregazzoni - can you please review this PR?

**Comment by pregazzoni** [comment]
@snowch on line 127 you have a typo:

```
 environment 'hostname', bigsql_hostame
```

should be `bigsql_hostname`

**Comment by snowch** [comment]
@pregazzoni fixed by the second commit in the PR :)

**Comment by pregazzoni** [comment]
Right all good

**Comment by snowch** [comment]
Thanks @pregazzoni

**Pull request merged**
